import { describe, expect, it } from "vitest";

import { validateRepositoryContract } from "../src/index.js";

describe("full repository contract schema composition", () => {
  it("parses a complete valid contract with agentic maintenance metadata", () => {
    const result = validateRepositoryContract({
      version: 1,
      repository: {
        name: "orders-service",
        purpose: {
          value: "Owns order creation and lifecycle management.",
          metadata: {
            source: "agent",
            review_status: "approval_required",
            review_required: true,
            proposal_id: "proposal_123"
          }
        },
        type: "service",
        primary_language: "typescript",
        languages: ["typescript"],
        root: ".",
        owners: ["platform"],
        tags: ["orders"]
      },
      metadata: {
        source: "agent",
        review_status: "approval_required",
        review_required: true,
        agent_run_id: "run_123",
        notes: "Generated by Contract Agent and waiting for human review."
      },
      maintenance: {
        maintained_by: ["contract-agent"],
        last_agent_update: "2026-07-28T12:00:00.000Z",
        review_required: true
      },
      environment: {
        DATABASE_URL: {
          name: "DATABASE_URL",
          required: true,
          secret: false,
          default_for_local: "postgres://postgres:postgres@localhost:5432/orders"
        }
      },
      services: {
        postgres: {
          id: "postgres",
          type: "postgresql",
          compose_service: "postgres",
          ports: [5432],
          environment: ["DATABASE_URL"]
        }
      },
      applications: {
        api: {
          id: "api",
          type: "api",
          working_directory: "apps/api",
          depends_on: ["postgres"],
          environment: ["DATABASE_URL"],
          ports: [3000]
        }
      },
      setup: {
        install: {
          command: "pnpm",
          args: ["install"]
        },
        steps: [
          {
            id: "migrate",
            kind: "run_migrations",
            command: {
              command: "pnpm",
              args: ["db:migrate"]
            }
          }
        ]
      },
      verification: {
        default: [
          {
            id: "typecheck",
            kind: "typecheck",
            command: {
              command: "pnpm",
              args: ["typecheck"]
            },
            components: ["api"]
          }
        ],
        rules: [
          {
            id: "api_changes",
            paths: ["apps/api/**"],
            checks: [
              {
                id: "api_tests",
                kind: "test",
                command: {
                  command: "pnpm",
                  args: ["test:api"]
                },
                components: ["api"]
              }
            ]
          }
        ]
      },
      generated_files: [
        {
          pattern: "apps/api/src/generated/**",
          generated_by: {
            command: "pnpm",
            args: ["generate"]
          },
          source_paths: ["openapi.yaml"]
        }
      ],
      sensitive_paths: [
        {
          pattern: ".env*",
          risk: "May contain local credentials."
        }
      ],
      unsafe_paths: [
        {
          pattern: "apps/api/src/generated/**",
          reason: "Generated code.",
          edit_instead: "openapi.yaml"
        }
      ],
      source_of_truth_paths: [
        {
          pattern: "openapi.yaml",
          governs: ["apps/api/src/generated/**"]
        }
      ],
      related_repositories: [
        {
          name: "checkout-web",
          provider: "github",
          repository_slug: "acme/checkout-web",
          relationship: "consumes_api",
          direction: "inbound"
        }
      ],
      external_systems: [
        {
          id: "stripe",
          name: "Stripe",
          type: "payment_provider",
          relationship: "consumes_api",
          direction: "outbound"
        }
      ],
      known_limitations: [
        {
          id: "payments-mocked-local",
          summary: "Payment provider calls are mocked locally.",
          impact: "Real payment behavior must be checked in staging.",
          status: "active",
          last_verified: "2026-07-28"
        }
      ]
    });

    expect(result.ok).toBe(true);
  });

  it("rejects unknown top-level fields according to the strict schema policy", () => {
    const result = validateRepositoryContract({
      version: 1,
      repository: {
        name: "orders-service",
        type: "service",
        primary_language: "typescript"
      },
      scanner_dump: {}
    });

    expect(result.ok).toBe(false);
    expect(result.issues[0]?.path).toBe("<root>");
    expect(result.issues[0]?.message).toContain("Unrecognized key");
  });

  it("detects duplicate component IDs across applications and services", () => {
    const result = validateRepositoryContract({
      version: 1,
      repository: {
        name: "orders-service",
        type: "service",
        primary_language: "typescript"
      },
      applications: {
        api: {
          id: "api",
          type: "api"
        }
      },
      services: {
        api: {
          id: "api",
          type: "http_api"
        }
      }
    });

    expect(result.ok).toBe(false);
    expect(result.issues).toContainEqual({
      path: "applications.api.id",
      message: "Duplicate component id across applications and services: api"
    });
  });

  it("detects invalid relative paths in composed sections", () => {
    const result = validateRepositoryContract({
      version: 1,
      repository: {
        name: "orders-service",
        type: "service",
        primary_language: "typescript",
        root: "/tmp/orders"
      },
      applications: {
        api: {
          id: "api",
          type: "api",
          working_directory: "/tmp/orders/apps/api"
        }
      },
      setup: {
        install: {
          command: "pnpm",
          args: ["install"],
          working_directory: "/tmp/orders"
        }
      }
    });

    expect(result.ok).toBe(false);
    expect(result.issues).toEqual([
      {
        path: "repository.root",
        message: "repository root must be relative to the repository root"
      },
      {
        path: "applications.api.working_directory",
        message: "application working_directory must be relative to the repository root"
      },
      {
        path: "setup.install.working_directory",
        message: "setup command working_directory must be relative to the repository root"
      }
    ]);
  });

  it("detects duplicate setup step IDs", () => {
    const result = validateRepositoryContract({
      version: 1,
      repository: {
        name: "orders-service",
        type: "service",
        primary_language: "typescript"
      },
      setup: {
        steps: [
          {
            id: "install",
            kind: "install_dependencies",
            command: {
              command: "pnpm",
              args: ["install"]
            }
          },
          {
            id: "install",
            kind: "custom",
            command: {
              command: "pnpm",
              args: ["setup"]
            }
          }
        ]
      }
    });

    expect(result.ok).toBe(false);
    expect(result.issues).toContainEqual({
      path: "setup.steps.1.id",
      message: "Duplicate setup step id: install"
    });
  });
});
