import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { buildFileInventory, createGeneratedFileDetector, scanRepository } from "../src/index.js";

describe("Generated file detector", () => {
  it("detects generated directories and links package regeneration commands", async () => {
    const root = await createFixture({
      "package.json": JSON.stringify({
        scripts: {
          codegen: "graphql-codegen"
        }
      }),
      "src/generated/graphql.ts": "/* eslint-disable */\nexport type User = { id: string };\n"
    });
    const inventory = await buildFileInventory({
      root,
      trackedFiles: ["package.json", "src/generated/graphql.ts"]
    });
    const result = await scanRepository({
      root,
      inventory,
      detectors: [createGeneratedFileDetector()]
    });

    expect(result.facts).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          kind: "generated.path_detected",
          confidence: "high",
          value: expect.objectContaining({
            path: "package.json",
            generator: "package-script",
            regenerationCommand: "graphql-codegen"
          })
        }),
        expect.objectContaining({
          kind: "generated.path_detected",
          confidence: "high",
          value: expect.objectContaining({
            path: "src/generated",
            regenerationCommand: "graphql-codegen",
            reason: "generated directory"
          })
        })
      ])
    );
  });

  it("detects OpenAPI and GraphQL generated file names", async () => {
    const root = await createFixture({
      "api/openapi.generated.ts": "// Auto generated by OpenAPI\n",
      "web/graphql.ts": "// generated\n"
    });
    const inventory = await buildFileInventory({
      root,
      trackedFiles: ["api/openapi.generated.ts", "web/graphql.ts"]
    });
    const result = await scanRepository({
      root,
      inventory,
      detectors: [createGeneratedFileDetector()]
    });

    expect(result.facts).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          kind: "generated.path_detected",
          confidence: "medium",
          value: expect.objectContaining({
            path: "api/openapi.generated.ts",
            generator: "openapi"
          })
        }),
        expect.objectContaining({
          kind: "generated.path_detected",
          confidence: "medium",
          value: expect.objectContaining({
            path: "web/graphql.ts",
            generator: "graphql-codegen"
          })
        })
      ])
    );
  });

  it("represents lockfiles as managed files without a regeneration command", async () => {
    const root = await createFixture({
      "pnpm-lock.yaml": "lockfileVersion: '9.0'\n"
    });
    const inventory = await buildFileInventory({
      root,
      trackedFiles: ["pnpm-lock.yaml"]
    });
    const result = await scanRepository({
      root,
      inventory,
      detectors: [createGeneratedFileDetector()]
    });

    expect(result.facts).toEqual([
      expect.objectContaining({
        kind: "generated.path_detected",
        confidence: "high",
        value: {
          path: "pnpm-lock.yaml",
          generator: "package-manager",
          regenerationCommand: undefined,
          reason: "lockfile",
          managed: true
        }
      })
    ]);
  });
});

async function createFixture(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "repo-knowledge-generated-file-"));

  for (const [path, contents] of Object.entries(files)) {
    const absolutePath = join(root, path);
    await mkdir(join(absolutePath, ".."), {
      recursive: true
    });
    await writeFile(absolutePath, contents);
  }

  return root;
}
